run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - misspell
    - unconvert
    - revive
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: go-palace
  revive:
    rules:
      - name: var-naming
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments
        disabled: true
