package room

// skipDirs is the directory-name blocklist used by Detect. Matches
// mempalace/room_detector_local.py:106-117 — intentionally SMALLER than
// the miner's full SKIP_DIRS set because room detection only needs to
// avoid obvious noise at the top level.
var skipDirs = map[string]struct{}{
	".git":         {},
	"node_modules": {},
	"__pycache__":  {},
	".venv":        {},
	"venv":         {},
	"env":          {},
	"dist":         {},
	"build":        {},
	".next":        {},
	"coverage":     {},
}

// folderRoomMap is the 74-entry folder-name → room-name dictionary copied
// verbatim from mempalace/room_detector_local.py:20-94.
var folderRoomMap = map[string]string{
	"frontend":       "frontend",
	"front-end":      "frontend",
	"front_end":      "frontend",
	"client":         "frontend",
	"ui":             "frontend",
	"views":          "frontend",
	"components":     "frontend",
	"pages":          "frontend",
	"backend":        "backend",
	"back-end":       "backend",
	"back_end":       "backend",
	"server":         "backend",
	"api":            "backend",
	"routes":         "backend",
	"services":       "backend",
	"controllers":    "backend",
	"models":         "backend",
	"database":       "backend",
	"db":             "backend",
	"docs":           "documentation",
	"doc":            "documentation",
	"documentation":  "documentation",
	"wiki":           "documentation",
	"readme":         "documentation",
	"notes":          "documentation",
	"design":         "design",
	"designs":        "design",
	"mockups":        "design",
	"wireframes":     "design",
	"assets":         "design",
	"storyboard":     "design",
	"costs":          "costs",
	"cost":           "costs",
	"budget":         "costs",
	"finance":        "costs",
	"financial":      "costs",
	"pricing":        "costs",
	"invoices":       "costs",
	"accounting":     "costs",
	"meetings":       "meetings",
	"meeting":        "meetings",
	"calls":          "meetings",
	"meeting_notes":  "meetings",
	"standup":        "meetings",
	"minutes":        "meetings",
	"team":           "team",
	"staff":          "team",
	"hr":             "team",
	"hiring":         "team",
	"employees":      "team",
	"people":         "team",
	"research":       "research",
	"references":     "research",
	"reading":        "research",
	"papers":         "research",
	"planning":       "planning",
	"roadmap":        "planning",
	"strategy":       "planning",
	"specs":          "planning",
	"requirements":   "planning",
	"tests":          "testing",
	"test":           "testing",
	"testing":        "testing",
	"qa":             "testing",
	"scripts":        "scripts",
	"tools":          "scripts",
	"utils":          "scripts",
	"config":         "configuration",
	"configs":        "configuration",
	"settings":       "configuration",
	"infrastructure": "configuration",
	"infra":          "configuration",
	"deploy":         "configuration",
}
