package dialect

// Data maps ported from Python dialect.py.
// Separated from dialect.go to keep files under 300 LOC guidance.

// EmotionCodes maps emotion names to their compact codes.
var EmotionCodes = map[string]string{
	"vulnerability":        "vul",
	"vulnerable":           "vul",
	"joy":                  "joy",
	"joyful":               "joy",
	"fear":                 "fear",
	"mild_fear":            "fear",
	"trust":                "trust",
	"trust_building":       "trust",
	"grief":                "grief",
	"raw_grief":            "grief",
	"wonder":               "wonder",
	"philosophical_wonder": "wonder",
	"rage":                 "rage",
	"anger":                "rage",
	"love":                 "love",
	"devotion":             "love",
	"hope":                 "hope",
	"despair":              "despair",
	"hopelessness":         "despair",
	"peace":                "peace",
	"relief":               "relief",
	"humor":                "humor",
	"dark_humor":           "humor",
	"tenderness":           "tender",
	"raw_honesty":          "raw",
	"brutal_honesty":       "raw",
	"self_doubt":           "doubt",
	"anxiety":              "anx",
	"exhaustion":           "exhaust",
	"conviction":           "convict",
	"quiet_passion":        "passion",
	"warmth":               "warmth",
	"curiosity":            "curious",
	"gratitude":            "grat",
	"frustration":          "frust",
	"confusion":            "confuse",
	"satisfaction":         "satis",
	"excitement":           "excite",
	"determination":        "determ",
	"surprise":             "surprise",
}

// EmotionSignals maps keywords found in text to emotion codes.
var EmotionSignals = map[string]string{
	"decided":    "determ",
	"prefer":     "convict",
	"worried":    "anx",
	"excited":    "excite",
	"frustrated": "frust",
	"confused":   "confuse",
	"love":       "love",
	"hate":       "rage",
	"hope":       "hope",
	"fear":       "fear",
	"trust":      "trust",
	"happy":      "joy",
	"sad":        "grief",
	"surprised":  "surprise",
	"grateful":   "grat",
	"curious":    "curious",
	"wonder":     "wonder",
	"anxious":    "anx",
	"relieved":   "relief",
	"satisf":     "satis",
	"disappoint": "grief",
	"concern":    "anx",
}

// FlagSignals maps keywords to their flag categories.
var FlagSignals = map[string]string{
	"decided":            "DECISION",
	"chose":              "DECISION",
	"switched":           "DECISION",
	"migrated":           "DECISION",
	"replaced":           "DECISION",
	"instead of":         "DECISION",
	"because":            "DECISION",
	"founded":            "ORIGIN",
	"created":            "ORIGIN",
	"started":            "ORIGIN",
	"born":               "ORIGIN",
	"launched":           "ORIGIN",
	"first time":         "ORIGIN",
	"core":               "CORE",
	"fundamental":        "CORE",
	"essential":          "CORE",
	"principle":          "CORE",
	"belief":             "CORE",
	"always":             "CORE",
	"never forget":       "CORE",
	"turning point":      "PIVOT",
	"changed everything": "PIVOT",
	"realized":           "PIVOT",
	"breakthrough":       "PIVOT",
	"epiphany":           "PIVOT",
	"api":                "TECHNICAL",
	"database":           "TECHNICAL",
	"architecture":       "TECHNICAL",
	"deploy":             "TECHNICAL",
	"infrastructure":     "TECHNICAL",
	"algorithm":          "TECHNICAL",
	"framework":          "TECHNICAL",
	"server":             "TECHNICAL",
	"config":             "TECHNICAL",
}

// stopWords are common filler words excluded from topic extraction.
// Port of Python _STOP_WORDS (dialect.py:161-295).
var stopWords = map[string]bool{
	"the": true, "a": true, "an": true, "is": true, "are": true,
	"was": true, "were": true, "be": true, "been": true, "being": true,
	"have": true, "has": true, "had": true, "do": true, "does": true,
	"did": true, "will": true, "would": true, "could": true, "should": true,
	"may": true, "might": true, "shall": true, "can": true,
	"to": true, "of": true, "in": true, "for": true, "on": true,
	"with": true, "at": true, "by": true, "from": true, "as": true,
	"into": true, "about": true, "between": true, "through": true,
	"during": true, "before": true, "after": true, "above": true,
	"below": true, "up": true, "down": true, "out": true, "off": true,
	"over": true, "under": true, "again": true, "further": true,
	"then": true, "once": true, "here": true, "there": true,
	"when": true, "where": true, "why": true, "how": true,
	"all": true, "each": true, "every": true, "both": true,
	"few": true, "more": true, "most": true, "other": true,
	"some": true, "such": true, "no": true, "nor": true, "not": true,
	"only": true, "own": true, "same": true, "so": true, "than": true,
	"too": true, "very": true, "just": true, "don": true, "now": true,
	"and": true, "but": true, "or": true, "if": true, "while": true,
	"that": true, "this": true, "these": true, "those": true,
	"it": true, "its": true, "i": true, "we": true, "you": true,
	"he": true, "she": true, "they": true, "me": true, "him": true,
	"her": true, "us": true, "them": true, "my": true, "your": true,
	"his": true, "our": true, "their": true, "what": true, "which": true,
	"who": true, "whom": true, "also": true, "much": true, "many": true,
	"like": true, "because": true, "since": true, "get": true,
	"got": true, "use": true, "used": true, "using": true,
	"make": true, "made": true, "thing": true, "things": true,
	"way": true, "well": true, "really": true, "want": true, "need": true,
}
